cleaning image tag from v letter

diff --git a/.github/workflows/build-and-push.yaml b/.github/workflows/build-and-push.yaml
--- a/.github/workflows/build-and-push.yaml
+++ b/.github/workflows/build-and-push.yaml
@@ -29,14 +29,29 @@ jobs:
           echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ vars.DOCKER_USERNAME }}" --password-stdin
           echo "Docker Hub login successful"
 
+      # Preparing tag name
+      - name: Prepare tag name
+        id: prepare_tag
+        run: |
+          git_tag_name=${{ github.ref_name }};
+          echo Verifying that the tag name matches the expected format...
+          if [[ ! "$git_tag_name" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Error: Tag name '$git_tag_name' does not match the expected format 'vX.Y.Z'.";
+            exit 1;
+          fi;
+          echo Cleaning the tag name from the first `v` character...
+          docker_image_tag_name=${git_tag_name:1};
+          echo "Tag name prepared: $git_tag_name";
+          echo "docker_image_tag_name=$docker_image_tag_name" >> $GITHUB_ENV;
+
       # For building and pushing the image we could use the official action, but here we do it manually for better tranansparency, debugging and portability
       # We also separate the build and push steps for isolating most common issues
       - name: Build multiplatform Docker image
         run: |
-          echo "Building Docker image ${{ vars.DOCKER_ORG }}/spfx:${{ github.ref_name }}..."
+          echo "Building Docker image ${{ vars.DOCKER_ORG }}/spfx:$docker_image_tag_name..."
           docker buildx build \
             --platform linux/amd64,linux/arm64/v8 \
-            --tag ${{ vars.DOCKER_ORG }}/spfx:${{ github.ref_name }} \
+            --tag ${{ vars.DOCKER_ORG }}/spfx:$docker_image_tag_name \
             --tag ${{ vars.DOCKER_ORG }}/spfx:latest \
             --tag ${{ vars.DOCKER_ORG }}/spfx:online \
             .
@@ -47,7 +62,7 @@ jobs:
           echo "Pushing Docker image from build cache..."
           docker buildx build \
             --platform linux/amd64,linux/arm64/v8 \
-            --tag ${{ vars.DOCKER_ORG }}/spfx:${{ github.ref_name }} \
+            --tag ${{ vars.DOCKER_ORG }}/spfx:$docker_image_tag_name \
             --tag ${{ vars.DOCKER_ORG }}/spfx:latest \
             --tag ${{ vars.DOCKER_ORG }}/spfx:online \
             --push \
